### PR TITLE
Update client.py

### PR DESCRIPTION
**Pull request by nkpetko**
~ Add an optional token verification check

### CODE REVIEW

**Comment by Julli4n** [comment]
.ROBLOSECURITY

**Comment by nkpetko** [comment]
Roblox.Authentication.Core

**Comment by bkordan** [comment]
OK, since when did you ever do python @nkpetko?

**Comment by Boegie19** [comment]
@nkpetko Would it not be better to do an api call to an endpoint with the key to see if it is valid yes or no? Since that then you can be 100% sure it works

**Comment by nkpetko** [comment]
@Boegie19 this verifies syntax, not jwt validity, read the comment I left

**Comment by Boegie19** [comment]
@nkpetko I know but why would you check syntax if you can just check jwt validity since if it is wrong it will come out anyway

**Comment by nkpetko** [comment]
@Boegie19 because checking Jwt validity is time consuming and wastes resources when you can just check syntax on the fly

**Comment by nkpetko** [comment]
Closing this because you simply love to ignore me

**Pull request closed without merging**
