### PR TITLE
Message Router API

### PR DESCRIPTION
**Pull request by rbx-nsg**
This API only consists of /v1/router/signalr, and will only support Studio messages (I haven't found out what the main channel/main accessKey is for open grid servers)

### CODE REVIEW

**Comment by jmkd3v** [comment]
This will not be accepted as it's not using our new endpoint system - the structure for building an endpoint URL should look something like this:
```py
from ro_py.utilities.url import url
endpoint = url("users")
```

**Comment by rbx-nsg** [comment]
I probably should have reviewed the new system before I made commits

**Comment by rbx-nsg** [comment]
The test url will be removed when I make it prod worthy

**Comment by jmkd3v** [comment]
Alright. If you have plans to add MessageRouter features, we'd prefer if those were added in this PR rather than waiting for another.

**Comment by rbx-nsg** [comment]
@jmkd3v The only thing that would ever be added to it is the ability to communicate with grid servers, but it will be a while until that happens, and I will probably ask you to add the changes when I find out how the grids' channel.

**Comment by jmkd3v** [comment]
Hm, I see.

**Comment by jmkd3v** [comment]
This is being closed as we move over to the rewrite branch. Feel free to redo your changes in the rewrite branch when it is ready.

**Comment by rbx-nsg** [comment]
Mbryhjkaldawad

**Pull request closed without merging**
